// Do not edit. This file is auto-generated by Prisma.
// Run `prisma generate` to regenerate this file.

export type { Account, Complaint, ComplaintCategory, ComplaintStatus, PasswordResetToken, Rating, Review, ReviewLike, ReviewReply, ReviewReport, ReportStatus, Role, Session, UniversityType, User, VerificationToken, AiSummary, University } from "@prisma/client";
